/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DefSwiper: typeof import('./components/DefSwiper/DefSwiper.vue')['default']
    GuessLike: typeof import('./components/GuessLike/GuessLike.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VkDataGoodsSkuPopup: typeof import('./components/vk-data-goods-sku-popup/vk-data-goods-sku-popup.vue')['default']
    VkDataInputNumberBox: typeof import('./components/vk-data-input-number-box/vk-data-input-number-box.vue')['default']
  }
}
